Repository wecode-bootcamp-korea/40-1st-Meet-Meat-frontend, pull requests merged in 2022-12, with the labels that each got.

#1 [40기 김민기]Add : 로그인페이지 레이아웃 완료
  package-lock.json
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청

#2 [40기 김민기]Add : footer레이아웃 완료
  public/images/Footer/gogi.png
  public/images/Nav/logo.png
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/pages/ProductList/ProductList.js
Labels: 멘토 리뷰 요청

#8 [40기 김윤아]Add: signUp 페이지 레이아웃 구현
  src/pages/MyPage/Mypage.js
  src/pages/MyPage/Mypage.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: Conflict 해결 요청

#12 Modify: 컨플릭트 주석 수정
  src/pages/SignUp/SignUp.js
Labels: 완료

#6 [40기 김민기] Add : 배송안내 페이지 레이아웃 구현
  public/images/Footer/pig.png
  src/assets/DeliveryPage/black.jpeg
  src/assets/DeliveryPage/coupon.png
  src/assets/DeliveryPage/delivery.png
  src/assets/DeliveryPage/dinner.png
  src/assets/DeliveryPage/fast.png
  src/assets/DeliveryPage/map.png
  src/assets/DeliveryPage/sale.png
  src/assets/DeliveryPage/search.png
  src/assets/DeliveryPage/today.png
  src/assets/DeliveryPage/truck.png
  src/pages/DeliveryPage/DeliveryPage.js
  src/pages/DeliveryPage/DeliveryPage.scss
  src/pages/Login/Login.scss
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#10 [40기 김민기]Add:상품 페이지 레이아웃 구현
  src/assets/ProductPage/check.png
  src/assets/ProductPage/white.png
  src/pages/ProductPage/ProductPage.js
  src/pages/ProductPage/ProductPage.scss
  src/pages/ProductPage/components/Option.js
  src/pages/ProductPage/components/Option.scss
  src/pages/ProductPage/components/ProductDetail.js
  src/pages/ProductPage/components/ProductDetail.scss
Labels: 멘토 리뷰 요청

#17 [40기 김윤아]Fix: Component명 변경 signUp -> signUpForm
  src/Router.js
  src/pages/SignUpForm/SignUpForm.js
  src/pages/SignUpForm/SignUpForm.scss
Labels: 완료

#11 [40기 김민기]Add: 장바구니페이지레이아웃
  src/pages/BasketPage/BasketPage.js
  src/pages/BasketPage/BasketPage.scss
Labels: 완료

#16 [40기 김윤아]Add: myPage 레이아웃 구현
  public/images/myPage/제목_없는_아트워크.png
  src/pages/Login/Login.js
  src/pages/MyPage/Mypage.js
  src/pages/MyPage/Mypage.scss
  src/pages/ProductList/ProductList.js
Labels: 멘토 리뷰 요청

#9 [40기 김윤아]Add: startSignUp 페이지 레이아웃 구현
  src/Router.js
  src/pages/Main/Section/BestProduct/BestProduct.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUpForm/SignUpForm.js
  src/pages/SignUpForm/SignUpForm.scss
Labels: 멘토 리뷰 요청

#20 [40기 김민기]Feature/nav바기능
  public/images/Nav/Hambuger/chicken.png
  public/images/Nav/Hambuger/cow.png
  public/images/Nav/Hambuger/duck.png
  public/images/Nav/Hambuger/pig.png
  src/components/Nav/Hambuger.js
  src/components/Nav/Hambuger.scss
  src/components/Nav/Nav.js
Labels: 멘토 리뷰 요청

#18 [40기 곽민경] Feature/product list 레이아웃 및 기능
  public/data/meatInfoList.json
  public/data/productList.json
  public/images/ProductDetail/gotPork.png
  public/images/ProductDetail/porkRib.png
  public/images/cartImage/blackCart.png
  public/images/cartImage/whiteCart.png
  src/components/ProductListTable/ProductListTable.js
  src/components/ProductListTable/ProductListTable.scss
  src/pages/Main/Main.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/Section/Banner/Banner.js
  src/pages/ProductList/Section/Banner/Banner.scss
  src/pages/ProductList/Section/Category/FilterCategory/FilterCategory.js
  src/pages/ProductList/Section/Category/FilterCategory/FilterCategory.scss
  src/pages/ProductList/Section/Category/ProductCategory/PRODUCTSORTS.js
  src/pages/ProductList/Section/Category/ProductCategory/ProductCategory.js
  src/pages/ProductList/Section/Category/ProductCategory/ProductCategory.scss
  src/pages/ProductList/Section/ProductMeatList/ProductListCard/ProductListCard.js
  src/pages/ProductList/Section/ProductMeatList/ProductListCard/ProductListCard.scss
  src/pages/ProductList/Section/ProductMeatList/ProductMeatList.js
Labels: 멘토 리뷰 요청

#19 [40기 김윤아]Add: review 페이지 레이아웃 구현
  public/data/ReviewList.json
  src/Router.js
  src/pages/ReviewPage/Review.js
  src/pages/ReviewPage/Review.scss
  src/pages/ReviewPage/ReviewListCard/ReviewListCard.js
  src/pages/ReviewPage/ReviewListCard/ReviewListCard.scss
Labels: 멘토 리뷰 요청

#22 [40기 김윤아]Add: login 기능 구현
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: 멘토 리뷰 요청

#24 [40기 김윤아]Add: mypage mockData 추가
  public/data/userData.json
  src/pages/MyPage/Mypage.js
  src/pages/MyPage/Mypage.scss
  src/pages/MyPage/UserInfo.js
  src/pages/MyPage/UserInfo.scss
Labels: 멘토 리뷰 요청

#23 [40기 김민기]feat:make-carousel
  public/images/ProductDetail/porkRib.PNG
  src/Router.js
  src/assets/Carosel/carosel1.jpg
  src/assets/Carosel/carosel2.jpg
  src/assets/Carosel/carosel3.jpg
  src/assets/Carosel/left.png
  src/assets/Carosel/right.png
  src/components/Carousel /Carousel.js
  src/components/Carousel /Carousel.scss
  src/pages/Main/Main.js
Labels: 멘토 리뷰 요청

#27 [40기 김민기]feature/main-page모달창
  public/data/meatInfoList.json
  src/Router.js
  src/components/Modal/Modal.js
  src/components/Modal/Modal.scss
  src/components/Nav/Nav.scss
  src/pages/OrderPage/OrderPage.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/Section/ProductMeatList/ProductListCard/ProductListCard.js
  src/pages/ProductList/Section/ProductMeatList/ProductListCard/ProductListCard.scss
Labels: 멘토 리뷰 요청

#26 [40기 곽민경] Feature/product page 기능 추가
  package-lock.json
  public/data/basketList.json
  public/data/data.json
  public/data/productDetail1.json
  public/data/productDetail2.json
  public/data/productInformation1.json
  public/data/productList.json
  public/images/ProductDetail/detail1.png
  public/images/ProductDetail/porkRib.png
  src/Router.js
  src/assets/ProductPage/arrow.png
  src/pages/DeliveryPage/DeliveryPage.js
  src/pages/ProductPage/ProductPage.js
  src/pages/ProductPage/ProductPage.scss
  src/pages/ProductPage/components/Option.js
  src/pages/ProductPage/components/Option.scss
  src/pages/ProductPage/components/Option/Option.js
  src/pages/ProductPage/components/Option/Option.scss
  src/pages/ProductPage/components/ProductDetail.js
  src/pages/ProductPage/components/ProductDetail.scss
  src/pages/ProductPage/components/ProductDetail/ProductDetail.js
  src/pages/ProductPage/components/ProductDetail/ProductDetail.scss
  src/pages/ReviewPage/Review.js
Labels: 멘토 리뷰 요청

#29 [40기 김윤아]Add: Link Component 연결
  public/index.html
  src/Router.js
  src/components/Nav/Hambuger.js
  src/components/Nav/Hambuger.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/config.js
  src/pages/BasketPage/BasketPage.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Main/Main.scss
  src/pages/Main/Section/Promotion/Promotion.js
  src/pages/Main/Section/Promotion/Promotion.scss
  src/pages/MyPage/Mypage.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/Section/Category/ProductCategory/ProductCategory.js
  src/pages/ProductList/Section/Category/ProductCategory/ProductCategory.scss
Labels: 멘토 리뷰 요청

#25 [40기 김민기]feat:order-page기능 구현
  public/data/UserInfo.json
  public/data/basket.json
  src/pages/OrderPage/OrderPage.js
  src/pages/OrderPage/OrderPage.scss
Labels: 멘토 리뷰 요청

#28 [40기 곽민경] Feature/basket page function 장바구니 페이지 기능
  public/data/basketList.json
  src/pages/BasketPage/BasketPage.js
  src/pages/BasketPage/BasketPage.scss
  src/pages/BasketPage/Section/BasketList/BasketListCard/BasketListCard.js
  src/pages/BasketPage/Section/BasketList/BasketListCard/BasketListCard.scss
  src/pages/BasketPage/Section/ReceiptSection/ReceiptSection.js
  src/pages/BasketPage/Section/ReceiptSection/ReceiptSection.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductPage/components/Option.js
Labels: 멘토 리뷰 요청

#30 [40기 김윤아]Modify: config 주소 변경
  src/components/Carousel /Carousel.scss
  src/components/Nav/Nav.js
  src/config.js
  src/pages/Login/Login.js
  src/pages/Main/Main.scss
  src/pages/MyPage/Mypage.js
Labels: 멘토 리뷰 요청
